enemy_color: "red"
#enemy_color: "blue"

#####-----神经网络参数-----#####
yolo_name: yolov5_trt
classify_model: ../assets/tiny_resnet.onnx
yolo11_model_path: ../assets/yolo11.xml
yolov8_model_path: ../assets/yolov8.xml
yolov5_model_path: ../assets/yolov5.xml
yolov5_trt_model_path: ../assets/yolov5a-fp16.engine
device: CPU
min_confidence: 0.8
use_traditional: true

#####-----ROI-----#####
roi: 
  x: 420
  y: 50
  width: 600
  height: 600

use_roi: false

#####-----传统方法参数-----#####
threshold: 150
max_angle_error: 45 # degree
min_lightbar_ratio: 1.5
max_lightbar_ratio: 20
min_lightbar_length: 8
min_armor_ratio: 1
max_armor_ratio: 5
max_side_ratio: 1.5
max_rectangular_error: 25 # degree

#####-----tracker参数-----#####
min_detect_count: 5
max_temp_lost_count: 40
outpost_max_temp_lost_count: 75

#####-----aimer参数-----#####
yaw_offset: -1 # degree -2.5
pitch_offset: 2 # degree 2
comming_angle: 60 # degree
leaving_angle: 20 # degree
decision_speed: 0.1 #8 # rad/s 判定是否小陀螺的速度阈值
high_speed_delay_time: 0.030 # s
#low_speed_delay_time: 0.015 # s planner use this value
low_speed_delay_time: 0.060 # s planner use this value

#####-----shooter参数-----#####
first_tolerance: 3 # 近距离射击容差，degree
second_tolerance: 2 # 远距离射击容差，degree
judge_distance: 2 #距离判断阈值
auto_fire: true # 是否由自瞄控制射击

#####-----相机参数-----#####
camera_name: "mindvision"
exposure_ms: 8
gamma: 3 #已经废弃
vid_pid: "f622:d13a"

# camera_name: "hikrobot"
# exposure_ms: 3
# gain: 10.0
# vid_pid: "2bdf:0001"

# camera_name: "daheng"
# exposure_ms: 2
# gamma: 2.85
# vid_pid: "KE0200010097"


#  1  0  0
#  0  1  0
#  0  0  1
R_gimbal2imubody: [1, 0, 0, 0, 1, 0, 0, 0, 1]

# # 重投影误差,数据来自相机内参: 0.1820px
# camera_matrix: [1785.4881526822305, 0, 672.4806478241826, 0, 1785.026019470562, 559.89603224794314, 0, 0, 1]
# distort_coeffs: [-0.076005079619881746, 0.11182817466388446, 0.0005362204787722057, -0.0027546300984895122, 0]

# # HK
# camera_matrix: [1783.59587, 0, 726.03868, 0, 1783.59342, 557.22206, 0, 0, 1]
# distort_coeffs: [-0.093721, 0.207229, 0.002192, -0.000909, 0]

# # MD1
# camera_matrix: [2530.4449, 0, 631.46289, 0, 2536.11534, 513.61409, 0, 0, 1]
# distort_coeffs: [-0.093721, 0.207229, 0.002192, -0.000909, 0]

# MD_HERO_UC
camera_matrix: [2467.89248,0, 648.86375, 0, 2468.83665, 467.29131, 0, 0, 1]
distort_coeffs: [-0.007537, 0.377799, 0.000311, 0.001523, 0.000000]

# #MD2
# camera_matrix: [1279.1579, 0, 660.93386, 0, 1285.86608, 539.38196, 0, 0, 1]
# distort_coeffs:  [-0.211299, 0.146132, 0.002248, 0.003142, 0.000000]

# # DH1
# camera_matrix: [1272.39905, 0, 618.61436, 0, 1272.1674, 522.77117, 0, 0, 1]
# distort_coeffs: [-0.200319, 0.123162, -0.000723, 0.000555, 0.000000]

# # DH2
# camera_matrix: 
# distort_coeffs: 


# 相机同理想情况的偏角: yaw1.44 pitch-7.28 roll0.96 degree
# 标定板到世界坐标系原点的水平距离: 1.13 m
# 标定板同竖直摆放时的偏角: yaw7.61 pitch13.92 roll-0.46 degree
# R_camera2gimbal: [-0.027182119030230909, -0.12616154330853446, 0.99163723074269183, -0.99949106557517331, 0.019998323121329122, -0.024853106601381177, -0.016695575474690555, -0.99180811252093692, -0.12664093215554434]
R_camera2gimbal: [0, 0, 1, -1, 0, 0, 0, -1, 0]  # 理想情况

# 机械偏置：表示相机坐标系原点相对于云台坐标系原点的平移向量
# 数据解读：t_camera2gimbal: [<X>, <Y>, <Z>]，单位：米，X取正值指相机位于云台中心前方，Y取正值指相机位于云台中心左侧，Z取正值指相机位于云台中心上方
# t_camera2gimbal: [0.13160669975045827, 0.10377721766577375, 0.024908271912914642]
t_camera2gimbal: [0.2142, 0.033, 0.0562]  # 理想情况
#qianhou 214.2mm zuoyou 33mm(板在相机右) shangxia 56.2mm

# #####-----cboard参数-----#####
# quaternion_canid: 0x100
# bullet_speed_canid: 0x101
# send_canid: 0xff
# can_interface: "can0"

#####-----gimbal参数-----#####
com_port: "/dev/pts/2"
yaw_kp: 0
yaw_kd: 0
pitch_kp: 0
pitch_kd: 0

#####-----planner-----#####
fire_thresh: 0.0001

# max_yaw_acc: 50
max_yaw_acc: 50
Q_yaw: [9e6, 0]
#Q_yaw: [6e6, 0] #zys 1.18
R_yaw: [1]

# max_pitch_acc: 100
max_pitch_acc: 100
Q_pitch: [9e6, 0]
R_pitch: [1]

#####-----buff_detector参数-----#####
model: "../assets/yolo11_buff_int8.xml"

#####-----buff_aimer参数-----#####
fire_gap_time: 0.700   # s
predict_time: 0.120     # s
