enemy_color: "red"
#enemy_color: "blue"

#####-----神经网络参数-----#####
yolo_name: yolov5_trt
classify_model: ../assets/tiny_resnet.onnx
yolo11_model_path: ../assets/yolo11.xml
yolov8_model_path: ../assets/yolov8.xml
yolov5_model_path: ../assets/yolov5.xml
yolov5_trt_model_path: ../assets/yolov5a-fp16-ampere.engine
#yolov5_trt_model_path: ../assets/yolov5a-fp16-orin.engine
#yolov5_trt_model_path: ../assets/yolov5a-fp16-ada.engine
device: CPU
min_confidence: 0.8
use_traditional: true

#####-----ROI-----#####
roi: 
  x: 420
  y: 50
  width: 600
  height: 600

use_roi: false

#####-----传统方法参数-----#####
threshold: 150
max_angle_error: 45 # degree
min_lightbar_ratio: 1.5
max_lightbar_ratio: 20
min_lightbar_length: 8
min_armor_ratio: 1
max_armor_ratio: 5
max_side_ratio: 1.5
max_rectangular_error: 25 # degree

#####-----tracker参数-----#####
min_detect_count: 5
max_temp_lost_count: 40 #15
outpost_max_temp_lost_count: 75 #75

#####-----相机参数-----#####
camera_name: "daheng"
exposure_ms: 5
gamma: 2.85
vid_pid: "KE0200010097"

#  1  0  0
#  0  1  0
#  0  0  1
R_gimbal2imubody: [1, 0, 0, 0, 1, 0, 0, 0, 1]

# HERO-3-08
# 重投影误差: 0.3751px
camera_matrix: [2519.6346787506677, 0, 650.62921967933346, 0, 2520.0186051833116, 479.96940027405566, 0, 0, 1]
distort_coeffs: [-0.0094591070249334542, 0.39935443155347256, 0.0011520327176720976, -0.0011554823923010092, 0]

# 相机同理想情况的偏角: yaw0.38 pitch-0.52 roll-1.26 degree
R_camera2gimbal: [-0.0064779369372593987, -0.0092959577573492862, 0.99993580869094323, -0.99973770966816744, -0.021906286121654128, -0.0066803065650612352, 0.021966979776106534, -0.99971680980052036, -0.009151611977478824]
t_camera2gimbal: [0.11612241824736501, -0.010136533135126701, 0.098385671795090585]

#####-----gimbal参数-----#####
com_port: /dev/pts/4

#####-----planner-----#####
fire_thresh: 0.0035

max_yaw_acc: 50 #50
Q_yaw: [9e6, 0]
R_yaw: [1]

# max_pitch_acc: 100
max_pitch_acc: 100
Q_pitch: [9e6, 0]
R_pitch: [1]

#####-----buff_detector参数-----#####
model: "../assets/yolo11_buff_int8.xml"

#####-----buff_aimer参数-----#####
fire_gap_time: 0.700   # s
predict_time: 0.120     # s

# 弹道解算模式，可选 "no_drag" (默认抛物线) 或 "hero" (带空气阻力迭代)
ballistic_model: "hero"

#####-----nav速度倍数（仅用于哨兵模式，导航相关）-----#####
velocity_n: 30

#####-----锁车中心参数-----#####
aim_center: false # 锁车中心
aim_center_min_distance: 4 # 触发锁车中心机制的最小距离，单位m，当装甲板距离车中心大于该值时优先锁定车中心点
armor_yaw_threshold: 10 # 锁车时装甲板yaw角度阈值，degree

#####-----UI显示配置-----#####
ui:
  enabled: true  # 是否启用UI显示